export const eCommerceGallery = [
  {
    id: 1,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-seller-dashboard-2026-05-21-16_17_45.png",
  },
  {
    id: 2,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-seller-orders-2026-05-21-16_23_20.png",
  },
  {
    id: 3,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-seller-orders-cffe38ab-85a0-4e82-91ac-0679f1ef7a8b-2026-05-21-16_24_20.png",
  },
  {
    id: 4,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-seller-products-2026-05-21-16_25_15.png",
  },
  {
    id: 5,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-seller-products-edit-f9ebaa79-7f74-4fd2-9558-a49a25e19974-2026-05-21-16_26_41.png",
  },
  {
    id: 6,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-user-profile-2026-05-21-16_18_18.webp",
  },
  {
    id: 7,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-user-profile-2026-05-21-16_19_44.png",
  },
  {
    id: 8,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-user-profile-2026-05-21-16_20_50.png",
  },
  {
    id: 9,
    url: "/assets/e-commerce-gallery/screencapture-pascalecloset-user-profile-2026-05-21-16_22_22.png",
  },
];

const bcd = (file: string) => `/assets/better-call-dante/${file}`;

export const bcallDanteGallery = [
  "main-dash-1.png",
  "main-dash-2.png",
  "main-dash-3.png",
  "main-dash-4.png",
  "main-dash-5.png",
  "main-dash-6.png",
  "main-dash-7.png",
  "main-dash-8.png",
  "main-dash-9.png",
  "main-dash-10.png",
  "main-dash-11.png",
  "main-dash-12.png",
  "agent-dash-1.png",
  "agent-dash-2.png",
  "agent-dash-3.png",
  "agent-dash-4.png",
  "agent-dash-5.png",
  "agent-dash-6.png",
  "agent-dash-7.png",
  "agent-dash-8.png",
  "agent-dash-9.png",
  "agent-dash-10.png",
  "agent-dash-11.png",
  "agent-dash-12.png",
  "agent-dash-13.png",
  "agent-dash-14.png",
  "agent-dash-15.png",
  "agent-dash-16.png",
  "agent-dash-17.png",
  "profile-1.png",
  "profile-2.png",
  "profile-3.png",
].map((file, index) => ({ id: index + 1, url: bcd(file) }));

export const daevaGallery = [
  {
    id: 1,
    url: "/assets/daeva-inmobiliaria/daeva-hero-cap.png",
  },
  {
    id: 2,
    url: "/assets/daeva-inmobiliaria/daeva-main-section-cap.png",
  },
  {
    id: 3,
    url: "/assets/daeva-inmobiliaria/daeva-filter-options-cap.png",
  },
  {
    id: 4,
    url: "/assets/daeva-inmobiliaria/daeva-prop-details-cap.png",
  },
  {
    id: 5,
    url: "/assets/daeva-inmobiliaria/daeva-reservations-dash-cap.png",
  },
  {
    id: 6,
    url: "/assets/daeva-inmobiliaria/daeva-admin-dash-cap.png",
  },
  {
    id: 7,
    url: "/assets/daeva-inmobiliaria/daeva-create-prop-cap-1.png",
  },
  {
    id: 8,
    url: "/assets/daeva-inmobiliaria/daeva-create-prop-cap-2.png",
  },
  {
    id: 9,
    url: "/assets/daeva-inmobiliaria/daeva-create-prop-cap-3.png",
  },
  {
    id: 10,
    url: "/assets/daeva-inmobiliaria/daeva-profile-cap-1.png",
  },
  {
    id: 11,
    url: "/assets/daeva-inmobiliaria/daeva-profile-cap-2.png",
  },
];

export const DISALLOWED_WORDS = [
  "puto",
  "puta",
  "putos",
  "putas",
  "puto/a",
  "pija",
  "verga",
  "mierda",
  "culo",
  "imbecil",
  "idiota",
  "boludo",
  "cabron",
  "pendejo",
  "coño",
  "carajo",
  "gilipollas",
  "basura",
  "la concha",
  "hijo de puta",
  "hija de puta",
  "malparido",
  "pelotudo",
  "concha",
  "estúpido",
  "estupido",
  "culiado",
  "culiao",
  "burro",
  "burra",
  "cagada",
  "cagó",
  "cago",
  "cualiadaso",
  "glande",
  "pito",
  "pinchila",
  "pajero",
  "pajera",
  "fuck",
  "fucking",
  "fucker",
  "motherfucker",
  "motherfucking",
  "shit",
  "shitty",
  "bullshit",
  "asshole",
  "bastard",
  "bitch",
  "damn",
  "crap",
  "dick",
  "prick",
  "wanker",
  "twat",
  "piss",
  "jerk",
  "dumbass",
];
